### ISSUE TITLE
Tracking Kubernetes and Cloudnative Community Day Progress

### ISSUE THREAD

**Issue by irvifa** [cloudnative-id/kubernetes-community-days#1]
# Maintainers

Taken from https://kubernetescommunitydays.org/organizing/
- @irvifa 
- @indrajati

# Getting Started Checklist

- [x] Verify that no other Kubernetes Community Day events are planned in your local area
- [x] Have a minimum of 3 local organizers (5 is recommended) from at least 3 different organizations. Each organizer needs to live in or just outside of the KCD location.
- [ ] Have a minimum of 3 sponsors**
- [x] Make sure that at least one organizer is an employee of a CNCF member, an Ambassador, or a CNCF project maintainer
- [x] Have a method to accept payments (sponsorships, tickets) and make payments (catering, A/V, other costs)
- [x] Verify that all organizers have agreed to these event guidelines and to abide by the Kubernetes Community Day Code of Conduct
- [x] Schedule an event date a minimum of 6 months after you file your event request with CNCF request submission, (9 months prior is preferable)
- [x] Agree to use Eventbrite for registration*
- [x] Agree to use Sched for organizing the program page*
- [ ] Confirm that one of the organizer’s employers will agree to serve as a fiscal sponsor*

# Checklist

## Assembling Your Team

- [ ] Finance and budgeting
- [x] Marketing and promotion
- [x] Sponsors
- [x] Call for Proposals (CFP) and schedule
- [x] Website updates
- [x] Registration
- [x] Venue, catering, local activities, and the hotel
- [x] T-shirts and other swag
- [ ] Evening event logistics

**Comment by girikuncoro** [comment]
Upstream tracker: https://github.com/cncf/kubernetes-community-days/issues/239
