### ISSUE TITLE
Google Platinum Sponsor Issue Tracker

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [cloudnative-id/kubernetes-community-days#38]
Tracking issue for Google Sponsorship
- [ ] Sign Letter of Agreement
- [x] Send Logo & Promotional Material
- [x]  Invite Google customer to submit CFP
- [x] Speaker bio, photo, talk title, talk description
- [ ] Sponsor booth person
- [x] Sponsor booth Information
  - description booth
  - promotional message
  - ads video : https://www.youtube.com/watch?v=Kxg2vDr6ido https://www.youtube.com/watch?v=vXBZl753NyY and https://www.youtube.com/watch?v=Rl5M1CzgEH4
  - website URL
- [x] Send Budget
