### ISSUE TITLE
NetApp Platinum Sponsor Issue Tracker

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [cloudnative-id/kubernetes-community-days#40]
Tracking issue for NetApp Sponsorship
- [x] Sign Letter of Agreement
- [x] Invite customer for NetApp/NetApp to submit CFP
- [x] Send Logo & Promotional Material
- [x] Speaker bio, photo, talk title, talk description
- [x] Sponsor booth person
- [x] Sponsor booth Information
  - description booth
  - promotional message
  - ads video
  - website URL
- [x] Send Budget
- [x] send post report
