### ISSUE TITLE
Keynote: Nikitha Tracking Issue

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [cloudnative-id/kubernetes-community-days#45]
- Concept: Presentation
- [x] Regist at community.cncf.io and join chapter https://community.cncf.io/kcd-indonesia/
- [x] Add Keynote in community.cncf.io
- [x] Calender Invitation Instruction
- [x] Calendar Invitation for 27 November 2021
- [x] Registration URL
- [x] update calender invitation to register with speaker URL & backstage URL
