### ISSUE TITLE
Keynote: Kelsey Hightower Tracking Issue

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [cloudnative-id/kubernetes-community-days#46]
Concept: Q&A Live
- [x] Regist at community.cncf.io and join chapter https://community.cncf.io/kcd-indonesia/
- [x] Add Keynote in community.cncf.io
- [x] Q&A questions
- [x] Moderators
  - [x] Imre Nagi @zufardhiyaulhaq 
- [x] Calender Invitation Instruction
- [x] Calendar Invitation with Details for 27 November 2021
- [x] update calender invitation to register with speaker URL & backstage URL
