### ISSUE TITLE
AWS Gold Sponsor Issue Tracker

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [cloudnative-id/kubernetes-community-days#52]
Tracking issue:
- [x] Sign Letter of Agreement
- [x] Send Logo & Promotional Material
- [x] Send Budget
- [x] Sponsor booth person
- [x] Sponsor booth Information
  - description booth : "Amazon Web Services (AWS) is the world’s most comprehensive and broadly adopted cloud platform, offering over 200 fully featured services from data centers globally. Millions of customers — including the fastest-growing startups, largest enterprises, and leading government agencies — are using AWS to lower costs, become more agile, and innovate faster."
  - promotional message
  - ads video https://www.youtube.com/watch?v=HibpGm-Lyww 
  - website URL https://amzn.to/2UaHB9O 
  - Ads lips for MC : ```Teman-teman bagi yang nanti menyimak sesi AWS yang akan dibawakan oleh Donnie jam 2 siang di Track 2, posting 1 hal yang teman2 pelajari dari sesi tersebut di social media, nanti akan dapat hadiah dari AWS. Untuk info lebih lanjut silahkan visit virtual booth AWS.```
  - [x] send post report
